<div class="main">
  <h1>Contact</h1>
  <h2></h2>
  <table width="80%" border="0" cellspacing="0" cellpadding="4">
    <tr>
      <th scope="row">Address: </th>
      <td>1114 Budapest, Bocskai út 7. II/4. </td>
    </tr>
    <tr>
      <th scope="row">Phone:</th>
      <td>+36 1 361-41-80 </td>
    </tr>
    <tr>
      <th scope="row">Mobile: </th>
      <td>+36 (30) 243-34-49</td>
    </tr>
    <tr>
      <th scope="row">E-mail:</th>
      <td><a href="mailto:schmidtv.ugyv@t-online.hu">schmidtv.ugyv@t-online.hu</a>, 
        <a href="mailto:iroda@jurisnet.hu">iroda@jurisnet.hu</a></td>
    </tr>
    <tr>
      <th scope="row">Webpage:</th>
      <td><a href="http://www.jurisnet.hu">www.jurisnet.hu</a></td>
    </tr>
  </table>
  <h1></h1>

   <a href="http://maps.google.hu/maps?f=q&amp;source=embed&amp;hl=hu&amp;geocode=&amp;q=1114+Budapest,+Bocskai+%C3%BAt+7.+&amp;sll=47.47449,19.045352&amp;sspn=0.002723,0.004823&amp;ie=UTF8&amp;hq=&amp;hnear=1114+Budapest,+XI.+ker%C3%BClet,+Bocskai+%C3%BAt+7&amp;ll=47.47655,19.0448&amp;spn=0.011602,0.018883&amp;z=15&amp;iwloc=A" target="_blank" class="noprint"><img src="styles/map_small.gif" alt="Bocskai ut 7."></a>
<img src="/styles/map_large.gif" alt="Terkep nyomtatashoz" width="100%" class="print">
   </div>
<!--main-->
<div class="sidebar"><img src="images/introduction.png" alt="Dr. Schmidt Valéria lawyer"></div>
<div style="clear:both;"></div>
