<img src="/styles/print_header.jpg" alt="Fejlec nyomtatashoz" width="100%" class="print">
<div id="header">
  <div id="cim"><span>Dr. Schmidt Valéria ügyvéd</span></div>
  <div id="lang">
    <ul>
      <li><a href="/index.shtml"><img src="styles/flag_hungarian.gif" alt="Váltás a magyar nyelvű oldalra."> magyar</a></li>
      <li><a href="/index_en.shtml"><img src="styles/flag_english.gif" alt="english"> english</a></li>
      <li><a href="/index_it.shtml"><img src="styles/flag_italian.gif" alt="italiano"> italiano</a></li>
      <li><a href="javascript:window.print();"><img src="styles/icon_print.gif" alt="Print this page"> Print this page</a></li>
    </ul>
  </div>
  <div id="logo" onclick="ManageTabPanelDisplay('tab1')" style="cursor:pointer;"></div>
  <div id="menu">
    <ul>
      <li><a onclick="ManageTabPanelDisplay('tab1')" href="#">Introduction</a></li>
      <li><a onclick="ManageTabPanelDisplay('tab2')" href="#">Specialities</a></li>
      <li><a onclick="ManageTabPanelDisplay('tab3')" href="#">Rates</a></li>
      <li><a onclick="ManageTabPanelDisplay('tab4')" href="#">Contact</a></li>
    </ul>
  </div>
</div>
