
<div class="main">
  <h1>Specialities</h1>
  <h2>Corporate law</h2>
  <h2>Economic and civil law</h2>
  <h2>Foundation, society</h2>
  <h2>Inheritance law</h2>
  <h2>Family law</h2>
  <h2>Real estate law</h2>
  <h2>Labour law</h2>
  <p></p>
  <p>Under construction.</p>
  
</div>
<div class="sidebar"><img src="images/introduction.png" alt="Dr. Schmidt Valéria ügyvéd"></div>
<div style="clear:both;"></div>