<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="hu-hu">
<head>
<title>Dr Schmidt Valéria ügyvéd</title>
<link rel="shortcut icon" href="styles/favicon.ico">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
<meta name="keywords" content="ügyvéd, ügyvédi iroda, jogász, budapesti ügyvéd, ügyvéd ingatlan, ingatlan adásvétel, házassági bontóper,  jogi tanács, társasági jog, ingatlanjog, családjog, öröklés,"> 
<meta name="description" content="Dr. Schmidt Valéria ügyvéd honlapja. Szakterületek: Társasági jog, Gazdasági és polgári jog, Alapítványok, Társasházi ügyek, Öröklési jog, Családjog, Ingatlanjog, Munkajog"> 
<meta name="google-site-verification" content="xMVB0piJYEGs2_xFB0fDjG5gPHMWdwk6kHec3LLa4Ac">

<link rel="stylesheet" type="text/css" href="styles/default_style.css"  title="default">
<link rel="alternate stylesheet" type="text/css" href="styles/style1.css" title="style1">
<link rel="stylesheet" type="text/css" href="styles/print.css" media="print">
<script type="text/javascript" src="scripts/styleswitcher.js"></script>
<script type="text/javascript" src="scripts/tabs.js"></script>
</head>

