
<div class="main">
  <h1>BEMUTATKOZÁS</h1>
  <h2>Üdvözlöm dr. Schmidt Valéria ügyvéd honlapján.</h2>
  <p>1980-ban végeztem az ELTE jogi karán, 1982-ben szakvizsgáztam. Külkereskedelmi nagyvállalatnál kezdtem pályafutásomat, majd építőipari vállalatnál szereztem gyakorlatot, 1985-tól 1990-ig munkaügyi bíró voltam a Fővárosi Munkaügyi Bíróságon. Ügyvédi irodámat 1990. évben alapítottam Budapesten. Több éves vállalati jogtanácsosi és a Fővárosi Munkaügyi Bíróságon munkaügyi bíróként eltöltött évek után a különböző területeken szerzett szakmai ismereteimmel, angol, olasz nyelvtudásommal igyekeztem ügyfeleim számára a hazai és nemzetközi igényeket egyaránt kielégítő jogi szolgáltatást nyújtani. </p>
  <p> Az utóbbi tíz évben különösen sokat foglalkoztam ingatlan adásvételi szerződések, a cégjog területén pedig társasági szerződések készítésével és cégmódosítási ügyek lebonyolításával. Nagy gyakorlattal rendelkezem a házassági bontóperek jogterületén, beleértve a házassági vagyonközösség megosztásra vonatkozó szerződések elkészítését, valamint az ezzel összefüggő peres képviseletet, amely sok esetben az ingatlanjog és a cégjog biztos ismeretét is megköveteli.</p>
  <p> Alapelvem az ügyfeleim elvárásának megfelelő minőségi szolgáltatás nyújtása, tisztességes, feladattal arányos ügyvédi munkadíj alkalmazásával. </p>
  <p> Nyelvtudás: angol felsőfokú, olasz társalgási szintű.</p>
  <p> </p>
</div>
<!--main-->
<div class="sidebar"><img src="images/pic3.jpg" alt="Dr. Schmidt Valéria ügyvéd"></div>
<div style="clear:both;"></div>

