
<div class="main">
  <h1>SZAKTERÜLETEIM</h1>
  <h2>Társasági jog</h2>
  <ul>
    <li>Cégalapítás és módosítás, társasági részesedés átruházás átalakulás (összeolvadás, egyesülés, kiválás).</li>
    <li>Cég  megszüntetés (végelszámolás, felszámolás), Tagok közötti jogviták és egyéb társasági jogi perekben jogi képviselet.</li>
    <li>Teljes körű cégképviselet, eseti vagy átalánydíjas megbízással.</li>
    <li>Társasági joggal összefüggő munkajogi tanácsadás, képviselet. </li>
  </ul>
  <h2>Gazdasági és polgári jog</h2>
  <p>Képviselet ellátása gazdálkodó szervezetek egymás közötti pereiben,</p>
  <ul>
    <li>szerződések készítése, véleményezése,</li>
    <li>Cégek jogi képviselete peres, peren kívüli eljárásokban,</li>
    <li>Képviselet csődeljárás, felszámolás, végelszámolási ügyekben </li>
    <li>Gazdasági és magán ügyfelek közötti  szavatossági perekben tanácsadás, jogi képviselet,</li>
    <li>kártérítési ügyekben tanácsadás ,jogi képviselet,</li>
  </ul>
  <p>Nem fizető adósok ügyvédi felszólítása, felszámolási eljárás kezdeményezése nem fizető adósokkal szemben.</p>
  <h2>Alapítványok, egyesületek</h2>
  <ul>
    <li>Alapító Okiratának elkészítése, képviselet a bírósági nyilvántartásba történő eljárásban</li>
  </ul>
  <h2>Öröklési jog</h2>
  <ul>
    <li>Tartási, életjáradéki, öröklési  szerződések elkészítése, </li>
    <li>Hagyatéki eljárásban jogi képviselet,</li>
    <li>Öröklési ügyekben tanácsadás, peres  képviselet</li>
    <li>Végrendelet készítése</li>
  </ul>
  <h2> Családjog</h2>
  <ul>
    <li>házassági bontóperben jogi tanácsadás, jogi képviselet, </li>
    <li>Házassági szerződések, vagyonmegosztási szerződések elkészítése,</li>
    <li>Gyermektartási, gyermek elhelyezési perekben tanácsadás, jogi képviselet,</li>
    <li>gyámhatósági ügyekben tanácsadás, jogi képviselet</li>
  </ul>
  <h2>Ingatlanjog - Adásvételi szerződések</h2>
  <ul>
    <li>Ingatlannal kapcsolatos szerződések készítése (bérlet, adásvétel, csaereszerződés, haszonélvezet alapítás,  használat, életjáradék, ajándékozás,  telekmegosztás) </li>
    <li>Ingatlanokkal kapcsolatos jogi tanácsadás </li>
    <li>Földhivatal előtti eljárásban képviselet ellátása teljes körű ingatlan-nyilvántartási ügyintézéssel, </li>
    <li>Ingatlanokkal kapcsolatos perekben (birtokvita, elbirtoklás, elővásárlási jog,  szerződés megtámadás) tanácsadás, peres képviselet, </li>
    <li>Ingatlanjog keretében az egyes szerződésekhez kapcsolódó egyes hatósági eljárások intézése (gyámhatósági eljárás, földhivatali eljárás, közigazgatási hatósági eljárás) </li>
  </ul>
  <h2>Munkajog</h2>
  <p>Munka Törvénykönyve, köztisztviselőkre, illetve közalkalmazottakra vonatkozó munkajogi szabályok speciális joggyakorlata alapján.</p>
  <ul>
    <li>Munkajogi kérdésekben tanácsadás, </li>
    <li>Munkavállalók, munkaadók peren kívüli vitáinak rendezése, peres képviselet, </li>
    <li>Munkaszerződések  véleményezése, elkészítése, módosítása, </li>
    <li>Munkaviszony megszüntetésével kapcsolatos iratszerkesztés, tanácsadás,  munkáltató intézkedése elleni jogorvoslat </li>
    <li>Munkajogi viták esetén munkaügyi peres képviselet, </li>
  </ul>
</div>
<div class="sidebar"><img src="images/pic2.jpg" alt="Dr. Schmidt Valéria ügyvéd"></div>
<div style="clear:both;"></div>

