<img src="/styles/print_header.jpg" alt="Fejlec nyomtatashoz" width="100%" class="print">
<div id="header">
  <div id="cim"><span>Dr. Schmidt Valéria avvocato</span></div>
  <div id="lang">
    <ul>
      <li><a href="/index.shtml"><img src="styles/flag_hungarian.gif" alt="magyar"> magyar</a></li>
      <li><a href="/index_en.shtml"><img src="styles/flag_english.gif" alt="english"> english</a></li>
      <li><a href="/index_it.shtml"><img src="styles/flag_italian.gif" alt="italiano"> italiano</a></li>
      <li><a href="javascript:window.print();"><img src="styles/icon_print.gif" alt="La stampa del lato"> La stampa del lato</a></li>
    </ul>
  </div>
  <div id="logo" onclick="ManageTabPanelDisplay('tab1')" style="cursor:pointer;"></div>
  <div id="menu">
    <ul>
      <li><a onclick="ManageTabPanelDisplay('tab1')" href="#">Introduzione</a></li>
      <li><a onclick="ManageTabPanelDisplay('tab2')" href="#">Specialità</a></li>
      <li><a onclick="ManageTabPanelDisplay('tab3')" href="#">Premi</a></li>
      <li><a onclick="ManageTabPanelDisplay('tab4')" href="#">Contatti</a></li>
    </ul>
  </div>
</div>
