
<div class="main">
  <h1>Specialità</h1>
  <h2>Diritto societario</h2>
  <h2>Economica e diritto civile</h2>
  <h2>Fondazioni, le associazioni</h2>
  <h2>Diritto di successione</h2>
  <h2>Diritto di famiglia</h2>
  <h2>Diritto immobiliare</h2>
  <h2>Diritto del lavoro</h2>
    <p></p>
  <p>Sotto carica.</p>

</div>
<div class="sidebar"><img src="images/introduction.png" alt="Dr. Schmidt Valéria ügyvéd"></div>
<div style="clear:both;"></div>